Add support for refresh-all

diff --git a/ansible-systemd b/ansible-systemd
--- a/ansible-systemd
+++ b/ansible-systemd
@@ -2,29 +2,26 @@
 
 set -eu
 
-if [ $# -ne 2 ]
-then
-    echo "Please specify action (build, push, refresh, run, scan) and platform, e.g. 'ubuntu/22.04'!"
-    exit 1
-fi
+function check_platform ()
+{
+    MATCH=0
+    echo "${1}" | grep -E '^[[:alnum:]]+/[[:alnum:]]+\.*[[:alnum:]]*/*$' > /dev/null && MATCH=1
+    if [ ${MATCH} -ne 1 ]
+    then
+        echo "Invalid platform format! Specify distro and release, separated by slash, e.g. 'ubuntu/22.04'."
+        exit 2
+    fi
 
-MATCH=0
-echo "${2}" | grep -E '^[[:alnum:]]+/[[:alnum:]]+\.*[[:alnum:]]*/*$' > /dev/null && MATCH=1
-if [ ${MATCH} -ne 1 ]
-then
-    echo "Invalid platform format! Specify distro and release, separated by slash, e.g. 'ubuntu/22.04'."
-    exit 2
-fi
+    export PLATFORM=$(echo ${1} | cut -d'/' -f1)
+    # Ensure we trim any trailing slashes
+    export RELEASE=$(echo ${1} | cut -d'/' -f2 | sed 's@/*$@@')
 
-export PLATFORM=$(echo ${2} | cut -d'/' -f1)
-# Ensure we trim any trailing slashes
-export RELEASE=$(echo ${2} | cut -d'/' -f2 | sed 's@/*$@@')
-
-if [ ! -f "${PLATFORM}/${RELEASE}/Dockerfile" ]
-then
-    echo 'Dockerfile not found! Please check if the specified platform is correct.'
-    exit 4
-fi
+    if [ ! -f "${PLATFORM}/${RELEASE}/Dockerfile" ]
+    then
+        echo 'Dockerfile not found! Please check if the specified platform is correct.'
+        exit 4
+    fi
+}
 
 function set_podman_aliases ()
 {
@@ -64,7 +61,7 @@ function find_exec ()
 
 function as_build ()
 {
-    ${exec} build --no-cache --pull --tag "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}" "${2}"
+    ${exec} build --no-cache --pull --tag "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}" "${1}"
 }
 
 function as_push ()
@@ -77,6 +74,8 @@ function as_scan ()
     if [ "${exec}" == 'docker' ]
     then
         ${exec} scout quickview "bviktor/ansible-systemd-${PLATFORM}:${RELEASE}"
+    else
+        echo "Scan is unsupported with podman, skipping..."
     fi
 }
 
@@ -92,35 +91,73 @@ function as_run ()
     ${exec} stop "${CONT_ID}"
 }
 
+function as_refresh ()
+{
+    as_scan
+    as_build "${1}"
+    as_scan
+    as_push
+}
+
+function as_refresh_all ()
+{
+    readarray -t all_platforms < <(ls -d */*)
+
+    for (( i=0; i<${#all_platforms[@]}; i++ ));
+    do
+        echo "Updating ${all_platforms[$i]} ..."
+        check_platform "${all_platforms[$i]}"
+        as_refresh "${all_platforms[$i]}"
+    done
+}
+
+if [ $# -ne 1 ] && [ $# -ne 2 ]
+then
+    echo "Please specify action (build, push, refresh, refresh-all, run, scan) and platform, e.g. 'ubuntu/22.04'!"
+    exit 1
+fi
+
+if [ $# -eq 1 ] && [ "$1" != 'refresh-all' ]
+then
+    echo "Invalid action!"
+    exit 1
+fi
+
+if [ $# -eq 2 ]
+then
+    check_platform "${2}"
+fi
+
 # Determine container solution
 export exec=$(find_exec)
 
 case "$1" in
     build)
-        as_build "${@}"
+        as_build "${2}"
         ;;
 
     push)
-        as_push "${@}"
+        as_push
         ;;
 
     scan)
-        as_push "${@}"
+        as_scan
         ;;
 
     refresh)
-        as_scan "${@}"
-        as_build "${@}"
-        as_scan "${@}"
-        as_push "${@}"
+        as_refresh "${2}"
+        ;;
+
+    refresh-all)
+        as_refresh_all
         ;;
 
     run)
-        as_run "${@}"
+        as_run
         ;;
 
     *)
-        echo "Invalid action! Valid actions are: build, push, refresh, run, scan."
+        echo "Invalid action! Valid actions are: build, push, refresh, refresh-all, run, scan."
         exit 3
         ;;
 esac
